export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				style={{
					height: "100svh",
					margin: 0,
					padding: 0,
					marginRight: "40px",
					marginLeft: "40px",
				}}
			>
				{children}
			</body>
		</html>
	);
}
